### ISSUE TITLE
Multiple native apps in the same monorepo

### ISSUE THREAD

**Issue by johanforssell** [dalinarkholin/example-typescript-monorepo#1]
I'm trying to add additional native apps into the repo - it's not working out.

After adding a new project in packages, essentially a copy of `packages/native`, I can no longer start the `native` app.

```
▶ yarn run native:start
yarn run v1.9.4
$ cd packages/native && node link-workspaces.js && node node_modules/react-native/local-cli/cli.js start --config ../../../../packages/native/rn-cli-config.js --reset-cache
fs.js:1061
  return binding.unlink(pathModule._makeLong(path));
                 ^

Error: EISDIR: illegal operation on a directory, unlink '/home/johan/dev/appar/packages/native/node_modules/react-native'
    at Object.fs.unlinkSync (fs.js:1061:18)
    at link (/home/johan/dev/appar/packages/native/link-script.js:10:8)
```

~

The content of `packages/native/node_modules`
```
▶ cd packages/native/node_modules && ls -la
total 112
drwxrwxr-x 28 johan johan 4096 sep  5 13:08 .
drwxrwxr-x  6 johan johan 4096 sep  5 13:08 ..
drwxrwxr-x  2 johan johan 4096 sep  5 13:08 ansi-styles
drwxrwxr-x 13 johan johan 4096 sep  5 13:08 @babel
drwxrwxr-x  4 johan johan 4096 sep  5 13:08 babylon
drwxrwxr-x  2 johan johan 4096 sep  5 13:08 .bin
drwxrwxr-x  2 johan johan 4096 sep  5 13:08 chalk
drwxrwxr-x 13 johan johan 4096 sep  5 13:08 core-js
drwxrwxr-x  3 johan johan 4096 sep  5 13:08 envinfo
drwxrwxr-x  5 johan johan 4096 sep  5 13:08 fbjs
drwxrwxr-x  3 johan johan 4096 sep  5 13:08 jest-docblock
drwxrwxr-x  4 johan johan 4096 sep  5 13:08 jest-haste-map
drwxrwxr-x  3 johan johan 4096 sep  5 13:08 jest-serializer
drwxrwxr-x  3 johan johan 4096 sep  5 13:08 jest-worker
drwxrwxr-x  4 johan johan 4096 sep  5 13:08 json5
drwxrwxr-x  4 johan johan 4096 sep  5 13:08 metro
drwxrwxr-x  4 johan johan 4096 sep  5 13:08 metro-babel7-plugin-react-transform
drwxrwxr-x  5 johan johan 4096 sep  5 13:08 metro-cache
drwxrwxr-x  6 johan johan 4096 sep  5 13:08 metro-minify-uglify
drwxrwxr-x  3 johan johan 4096 sep  5 13:08 metro-source-map
drwxrwxr-x  2 johan johan 4096 sep  5 13:08 mime-db
drwxrwxr-x  2 johan johan 4096 sep  5 13:08 mime-types
drwxrwxr-x  5 johan johan 4096 sep  5 13:08 plist
drwxrwxr-x  3 johan johan 4096 sep  5 13:08 pretty-format
drwxrwxr-x  5 johan johan 4096 sep  5 13:08 react-devtools-core
drwxrwxr-x 15 johan johan 4096 sep  5 13:08 react-native
drwxrwxr-x  2 johan johan 4096 sep  5 13:08 supports-color
drwxrwxr-x  3 johan johan 4096 sep  5 13:08 xmlbuilder
```
~

If I remove the added `packages/theOtherApp` and run `yarn install` in the root, I can run it again. 
`packages/native/node_modules` is back to normal:
```
total 20
drwxrwxr-x 5 johan johan 4096 sep  5 12:51 .
drwxrwxr-x 6 johan johan 4096 sep  5 12:20 ..
drwxrwxr-x 5 johan johan 4096 sep  5 12:50 @babel
drwxrwxr-x 2 johan johan 4096 sep  5 12:50 .bin
drwxrwxr-x 3 johan johan 4096 sep  5 12:51 .cache
lrwxrwxrwx 1 johan johan   47 sep  5 12:51 react-native -> /home/johan/dev/appar/node_modules/react-native
```

Any ideas?

**Comment by dalinarkholin** [comment]
@johanforssell Thanks for the report, and thanks for using the repo.

I was unable to reproduce your specific error, but it looks like yarn-workspaces wasn't acting properly. Make sure you have the latest yarn installed via `npm install yarn -g`(make sure you have 1.7.0 or higher)

In any case, I went ahead and added an example in new branch called "mutiple-native-projects" Feel free to check that branch out.

I also added instructions for adding a second native project in the master branch README.md, those instructions are a first pass at it. Im not sure all the steps are needed, but it seemed to work for me. 

Let me know if you get it resolved. Thanks
